import xml.etree.ElementTree as ET
from pathlib import Path
import re
import sys
import hashlib


def stable_id(stmt: str) -> str:
    """
    Creates a short, consistent ID for a statement.

    Why we need this:
    - We use it as a node ID in the graph
    - Same statement always produces same ID
    """
    return hashlib.md5(stmt.encode()).hexdigest()[:10]

def extract_short_id(statement: str):
    """
    Creates a readable ID for a FlowDroid statement.

    Idea:
    - Try to use method name if possible (i.e. getLatitude for LocationLeak1)
    - Otherwise, fallback to shortened raw text
    """
    # Try to find method name inside <Class: type method()>
    method_match = re.search(r"<[^:]+: [^ ]+ (\w+)\(", statement)
    # Try to find first string literal (like "Latitude")
    literal_match = re.search(r'\("([^"]+)"', statement)  # get first quoted literal, e.g. "Latitude"

    # If we found a method name
    if method_match:
        base = method_match.group(1)
        # If we also found a string literal, combine them
        if literal_match:
            return f"{base}_{literal_match.group(1)}"
        # Otherwise just return the method name
        return base

    # If no method found, clean and shorten the statement
    clean = statement.replace("\n", " ").strip()
    return clean[:60]

# Regex that matches method calls like:
# virtualinvoke obj.<Class: type method(...)>(args)
METHOD_CALL_RE = re.compile(
    r'(virtualinvoke|staticinvoke)\s+<?([^:]+):\s+([^ ]+)\s+(\w+)\((.*?)\)>?\((.*)\)'
)
# Regex that matches method calls like:
# x = something
ASSIGN_RE = re.compile(r'^(\$\w+|\w+(?:\[\d+\])?)\s*=\s*(.*)$')
# Regex that matches field writes like:
# <Class: type field> = value
FIELD_WRITE_RE = re.compile(
    r'<([^:]+):\s+([^ ]+)\s+(\w+)>\s*=\s*(.+)'
)


def extract_source_line(stmt: str) -> str:
    """
    Converts FlowDroid IR (low-level representation) into a simplified Java-like assignment.

    Example input:
        lon = virtualinvoke loc.<Location: double getLongitude()>()

    Output:
        double lon = loc.getLongitude()
    """
    # Step 1: Try to match a method call pattern
    m = METHOD_CALL_RE.search(stmt)
    # If no method call if found, just return the raw statement
    if not m:
        return stmt

    # Extract parts from regex:
    # invoke_type = virtualinvoke / staticinvoke
    # cls = class name (android.location.Location)
    # ret = return type (double, String, etc.)
    # method = method name (getLongitude)
    # sig = method signature (unused here)
    # args = arguments passed to method
    invoke_type, cls, ret, method, sig, args = m.groups()

    # Step 2: Extrzct the left-hand side variable (e.g. lon in LocationLeak1)
    lhs = stmt.split("=")[0].strip()

    # Step 3: Try to guess the object (receiver) calling the method
    # Example: loc.<Location: ...>
    receiver_match = re.search(r'([\w$#]+)\.<', stmt)
    # If found, use it; otherwise fallback to "obj"
    receiver = receiver_match.group(1) if receiver_match else "obj"
    # Clean receiver (remove #5 noise)
    receiver = receiver.split("#")[0]

    # Step 4: Build simplified Java-like code
    # Example:
    # double long = loc.getLongitude()
    return f"{ret} {lhs} = {receiver}.{method}()"


def extract_sink_line(stmt: str) -> str:
    """
    Converts FlowDroid sink IR into a simplified Java-like call.

    Example input:
        staticinvoke <Log: int d(String,String)>("Longtitude", $u2)

    Output:
        Log.d(Longtitude, $u2)
    """
    # Step 1: Match method call pattern in IR
    m = METHOD_CALL_RE.search(stmt)
    # If parsing fails, return raw statement
    if not m:
        return stmt
    
    # Extract components
    _, cls, _, method, _, args = m.groups()

    # Step 2: Get only class name (remove full package path)
    # Example:
    # android.util.Log -> Log
    class_name = cls.split(":")[0].split(".")[-1]

    # Step 3: Build simplified sink call
    # We reuse original arguments (important for our taint tracking)
    return f"{class_name}.{method}({args})"


def classify_node(stmt: str) -> str:
    """
    Labels a statement type so we can decide how to treat it.

    Categories:
    - noise: irrelevant compiler-generated stuff
    - semantic: meaningful operations (method calls)
    - assign: simple assignments
    """
    s = stmt.strip()

    # Ignore synthetic helper methods generated by the compiler
    if "access$" in s:
        return "noise"

    # Ignore dummy entry points
    if "dummyMain" in s:
        return "noise"

    # Ignore Android internal parameters
    if "@parameter" in s or "@this" in s:
        return "noise"

    # Ignore constructors
    if "specialinvoke" in s and "<init>" in s:
        return "noise"

    # Method calls are important (sources/sinks/transformations)
    if "virtualinvoke" in s or "staticinvoke" in s:
        return "semantic"

    # Simple assignment
    if "=" in s:
        return "assign"

    return "unknown"


def reconstruct_java_line(stmt: str) -> str:
    """Reconstruct the original Java source code line for a statement"""
    s = stmt.strip()

    # Pattern 1: Double.toString(x)
    m = re.search(
        r'(\$\S+)\s*=\s*staticinvoke\s+<java\.lang\.Double:\s+java\.lang\.String\s+toString\(double\)>\((\w+)\)',
        s
    )
    if m:
        _, var = m.groups()
        return f"String tmp = Double.toString({var});"

    # Pattern 2: field write
    m = re.search(
        r'<[^:]+:\s+([\w\.]+)\s+(\w+)>\s*=\s*(\$\S+)',
        s
    )
    if m:
        _, field, rhs = m.groups()
        return f"{field} = {rhs};"

    # Pattern 3: StringBuilder append
    m = re.search(r'append\((\$\w+)\)', s)
    if m:
        return f"append({m.group(1)})"

    # fallback
    return clean_label(stmt)


def is_meaningful_node(stmt: str) -> bool:
    # Skip compiler-generated accessor methods and very short generic statements
    s = stmt.strip()

    # 1) Remove lifecycle + builder noise
    noise_patterns = [
        "access$",
        "dummyMain",
        "@parameter",
        "@this",
        "return",
        "<init>",
        "StringBuilder",
        "append(",
        "toString()",
        "onResume()",
    ]
    if any(p in s for p in noise_patterns):
        return False

    # 2) Keep only real data movement
    if "getLatitude" in s or "getLongitude" in s:
        return True

    if "Double: java.lang.String toString" in s:
        return True

    if re.search(r'\.<.*>\s*=', s):  # field write
        return True

    return False


def parse_method_signature(method_sig: str):
    """
    Extract class name and method name from FlowDroid signature.
    Example:
        <de.ecspride.LocationLeak1: void onResume()>
        -> ("LocationLeak1", "onResume")
    """
    if not method_sig:
        return ("unknown", "unknown")
    m = re.search(r'<([\w\.\$]+):\s+[\w\.\[\]]+\s+(\w+)\(', method_sig)
    if not m:
        return ("unknown", "unknown")
    full_class = m.group(1)
    method = m.group(2)
    simple_class = full_class.split(".")[-1]
    return (simple_class, method)


def clean_label(stmt: str) -> str:
    """Make the statement for intermediate nodes cleaner"""
    s = stmt.strip()

    if "virtualinvoke" in s:
        m = re.search(r"<([^:]+): .* (\w+)\(", s)
        if m:
            return m.group(2)

    if "staticinvoke" in s:
        m = re.search(r"<([^:]+): .* (\w+)\(", s)
        if m:
            return m.group(2)

    return s[:40]


def parse_flowdroid_xml(file_path: str):
    """
    Parses a FlowDroid XML log and extracts the sources, sinks, and intermediate variables.
    Returns: dict with "nodes" and "edges" suitable for graph construction.
    """
    file_path = Path(file_path)
    if not file_path.exists():
        raise FileNotFoundError(f"{file_path} does not exist")
    
    tree = ET.parse(file_path)
    root = tree.getroot()

    nodes = []
    edges = []

    # Keep track of node and edge IDs to avoid duplicates
    node_set = set()
    edge_set = set()

    # Iterate through each <Result> tag in the XML
    for result in root.findall(".//Result"):
        # Extract the sink
        sink_elem = result.find("Sink")
        if sink_elem is None:
            continue
        sink_stmt = sink_elem.attrib.get("Statement")
        sink_method = sink_elem.attrib.get("Method")
        sink_id = stable_id(sink_stmt)
        sink_name = extract_sink_line(sink_stmt)
        sink_line = sink_elem.attrib.get("LineNumber")
        cls, method_name = parse_method_signature(sink_method)

        if sink_id not in node_set:
            nodes.append({
                "id": sink_id,
                "label": sink_name, # Reconstructed Java-like line
                "raw": sink_stmt, # Original IR for debugging
                "type": "sink",
                "class": cls,
                "method": method_name,
                "full_method": sink_method,
                "line": sink_line
            })
            node_set.add(sink_id)
        
        # Extract sources
        sources_elem = result.find("Sources")
        if sources_elem is None:
            continue
            
        for source_elem in sources_elem.findall("Source"):
            source_stmt = source_elem.attrib.get("Statement")
            source_method = source_elem.attrib.get("Method")
            source_id = stable_id(source_stmt)
            source_name = extract_source_line(source_stmt)
            source_line = source_elem.attrib.get("LineNumber")
            cls, method_name = parse_method_signature(source_method)

            if source_id not in node_set:
                nodes.append({
                    "id": source_id,
                    "label": source_name,
                    "raw": source_stmt,
                    "type": "source",
                    "class": cls,
                    "method": method_name,
                    "full_method": source_method,
                    "line": source_line
                })
                node_set.add(source_id)

            # Extract the taint path elements as the intermediate edges
            taint_path = source_elem.find("TaintPath")
            if taint_path is not None:
                last_var = source_id
                pending_conversion = None

                for path_elem in taint_path.findall("PathElement"):
                    intermediate_stmt = path_elem.attrib.get("Statement")
                    intermediate_method = path_elem.attrib.get("Method")

                    if not is_meaningful_node(intermediate_stmt):
                        continue

                    # 1) Detect Double.toString
                    if "Double: java.lang.String toString" in intermediate_stmt:
                        m = re.search(r'\(([^)]+)\)', intermediate_stmt)
                        if m:
                            pending_conversion = m.group(1)
                        continue

                    # 2) Detect field write
                    field_match = re.search(
                        r'<[^:]+:\s+java\.lang\.String\s+(\w+)>',
                        intermediate_stmt
                    )

                    if field_match and pending_conversion:
                        field_name = field_match.group(1)

                        label = f"{field_name} = Double.toString({pending_conversion});"
                        intermediate_id = stable_id(label)

                        if intermediate_id not in node_set:
                            nodes.append({
                                "id": intermediate_id,
                                "label": label,
                                "type": "intermediate",
                                "method": intermediate_method
                            })
                            node_set.add(intermediate_id)

                        edge = (last_var, intermediate_id)
                        if edge not in edge_set:
                            edges.append({"from": last_var, "to": intermediate_id})
                            edge_set.add(edge)

                        last_var = intermediate_id
                        pending_conversion = None
                        continue

                # connect to sink
                edge = (last_var, sink_id)
                if edge not in edge_set:
                    edges.append({"from": last_var, "to": sink_id})
                    edge_set.add(edge)

    return {
        "nodes": nodes,
        "edges": edges
    }


if __name__ == "__main__":
    import json
    if len(sys.argv) != 2:
        print("Usage: python3 xml_parser.py <XML_NAME>")
        sys.exit(1)
    try:
        # Fetch the XML file
        xml_file = f"data/xml_results/{sys.argv[1]}.xml"
        # Parse the XML file
        parsed = parse_flowdroid_xml(xml_file)
        #print(json.dumps(parsed, indent=2))
    except Exception as e:
        print(f"[xml_parser.py] Error: {e}")



# OLD FUNCTIONS SAVED AS BACKUP
"""
def extract_sink_line(sink_stmt: str) -> str:
    ""
    Reconstruct a Java-like sink line from FlowDroid IR.
    Example:
        staticinvoke <android.util.Log: int d(java.lang.String,java.lang.String)>("Longtitude", $u2)
        -> Log.d(longitude)
    ""
    print("SINK:", sink_stmt)
    # Split the statement by paces
    parts = sink_stmt.split(" ")
    print(parts)

    # Get the sink variable name
    var_name = parts[0]

    # Get the method that was called in the sink (last element)
    raw_sink_method = parts[-1]
    sink_method = raw_sink_method.split("(")[0]
    
    # Get the type of the sink method
    raw_sink_method_type = parts[len(parts)-2]
    sink_method_type = raw_sink_method_type.split(".")[-1]

    # Get the name of the calling class
    raw_receiver = parts[3]
    receiver = raw_receiver.split(".")[0].split("#")[0]


    # Build Java-like line
    print(f"{sink_method_type} {var_name} = {receiver}.{sink_method}()\n\n")
    return f"{sink_method_type} {var_name} = {receiver}.{sink_method}()"
"""
"""
def extract_source_line(source_stmt: str) -> str:
    ""
    Reconstruct a Java-like source line from FlowDroid IR.
    Example:
        lon = virtualinvoke loc.<Location: double getLongitude()>()
        -> double lon = loc.getLongitude()
    ""
    print("SOURCE:", source_stmt)
    # Split the statement by paces
    parts = source_stmt.split(" ")
    print(parts)

    # Get the source variable name
    var_name = parts[0]

    # Get the method that was called in the source (last element)
    raw_source_method = parts[-1]
    source_method = raw_source_method.split("(")[0]
    
    # Get the type of the source method
    raw_source_method_type = parts[len(parts)-2]
    source_method_type = raw_source_method_type.split(".")[-1]

    # Get the name of the calling class
    raw_receiver = parts[3]
    receiver = raw_receiver.split(".")[0].split("#")[0]


    # Build Java-like line
    print(f"{source_method_type} {var_name} = {receiver}.{source_method}()\n\n")
    return f"{source_method_type} {var_name} = {receiver}.{source_method}()"
"""